[package]
name = "t"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
billboard = "0.1.0"
colored = "2.0.0"
skim = "0.9.4"
spinners = "2.0.0"
